apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: hello-world-service
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      targetPort: 8000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: hello-world
  type: NodePort